export const dependencies = {
  'expo-app': {
    '@expo/metro-config': '~57.0.3',
    '@expo/metro-runtime': '~57.0.3',
    '@ronas-it/react-native-common-modules': '~2.0.1',
    'react-native-mmkv': '^4.3.2',
    'expo-constants': '~57.0.3',
    'expo-dev-client': '~57.0.5',
    'expo-router': '~57.0.3',
    'react-native-safe-area-context': '~5.7.0',
    'react-native-screens': '4.25.2',
    expo: '~57.0.2',
    'expo-linking': '~57.0.1',
    'expo-splash-screen': '~57.0.2',
    'expo-status-bar': '~57.0.0',
    'expo-system-ui': '~57.0.0',
    'expo-updates': '~57.0.6',
    'expo-insights': '~57.0.2',
    'expo-localization': '~57.0.0',
    'i18n-js': '~4.5.1',
    'lodash-es': '^4.18.1',
    react: '~19.2.7',
    'react-dom': '~19.2.7',
    'react-native': '~0.86.0',
    'react-native-svg': '~15.15.4',
    'react-native-svg-transformer': '~1.5.1',
  },
  'next-app': {
    'next-intl': '~4.13.1',
    'lodash-es': '^4.18.1',
    'class-transformer': '~0.5.1',
    next: '~16.3.5',
    react: '~19.2.7',
    'react-dom': '~19.2.7',
  },
  'api-client': {
    '@ronas-it/axios-api-client': '^0.3.0',
  },
  auth: {
    luxon: '^3.7.2',
  },
  'next-auth': {
    'js-cookie': '^3.0.8',
  },
  'rn-styles': {
    'react-native-unistyles': '^3.2.5',
    'react-native-edge-to-edge': '^1.8.1',
    'react-native-nitro-modules': '0.35.10',
  },
  'ui-kit': {
    'expo-constants': '~57.0.3',
    'react-native-reanimated': '4.5.1',
    'react-native-worklets': '0.10.0',
    'expo-image': '~57.0.0',
    'expo-router': '~57.0.3',
    'react-native-toast-message': '^2.3.3',
    'react-native-keyboard-controller': '1.21.9',
  },
  store: {
    '@ronas-it/rtkq-entity-api': '^1.1.1',
    'react-redux': '^9.3.0',
  },
  form: {
    '@hookform/resolvers': '^5.4.0',
    'react-hook-form': '^7.80.0',
    yup: '^1.7.1',
  },
  sentry: {
    expo: {
      '@sentry/react-native': '~8.17.1',
    },
    next: {
      '@sentry/nextjs': '^10.63.0',
    },
  },
  nuqs: {
    nuqs: '^2.9.0',
  },
  mantine: {
    '@mantine/core': '^9.0.0',
    '@mantine/hooks': '^9.0.0',
    clsx: '^2.1.1',
  },
};

export const devDependencies = {
  'code-checks': {
    '@eslint/compat': '^1.4.0',
    '@eslint/eslintrc': '^3.3.1',
    '@eslint/js': '^9.37.0',
    eslint: '^9.37.0',
    prettier: '^3.6.2',
    'eslint-config-prettier': '^10.1.8',
    'eslint-import-resolver-typescript': '^4.4.4',
    'eslint-plugin-import-x': '^4.17.1',
    'eslint-plugin-jsx-a11y': '^6.10.2',
    'eslint-plugin-react': '^7.37.5',
    'eslint-plugin-react-hooks': '^7.0.0',
    'eslint-plugin-react-native': '^5.0.0',
    'eslint-plugin-react-native-unistyles': '^3.0.7',
    'eslint-plugin-unused-imports': '^4.2.0',
    husky: '^9.1.7',
    '@stylistic/eslint-plugin': '^4.4.1',
    '@typescript-eslint/eslint-plugin': '^8.46.0',
    '@typescript-eslint/parser': '^8.46.0',
    'tsc-files': '^1.1.4',
    'typescript-eslint': '^8.46.0',
    stylelint: '^17.12.0',
    'stylelint-config-standard-scss': '^17.0.0',
  },
  'expo-app': {
    '@types/lodash-es': '^4.17.12',
    '@types/react': '~19.2.0',
    '@types/react-dom': '~19.2.0',
    '@expo/cli': '^57.0.4',
    'babel-preset-expo': '~57.0.1',
    'reactotron-react-native': '^5.1.18',
    'reactotron-redux': '^3.2.1',
    metro: '^0.84.2',
    'metro-config': '~0.84.2',
  },
  'next-app': {
    'eslint-config-next': '~16.3.5',
    '@types/lodash-es': '^4.17.12',
    '@types/react': '~19.2.0',
    '@types/react-dom': '~19.2.0',
    'babel-plugin-react-compiler': '^1.0.0',
  },
  'repo-config': {
    syncpack: '^15.3.2',
    'cross-env': '^10.1.0',
    typescript: '~6.0.3',
  },
  auth: {
    '@types/luxon': '3.7.2',
  },
  'next-auth': {
    '@types/js-cookie': '^3.0.6',
  },
  mantine: {
    postcss: '^8.5.8',
    'postcss-preset-mantine': '^1.18.0',
    'postcss-simple-vars': '^7.0.1',
  },
};
